---

- name: Creating Cloud Support user in the OCI
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    parent_compartment_ocid: "{{ lookup('env', 'PARENT_COMPARTMENT_OCID') }}"
    group_name: "TCBCloudAdmin"
    domain: "@gmail.com"
    users:
      - praful9080
      

  tasks:
   - name: Validating prerequisites
     fail:
       msg: "Variable {{item}} not defined. Please, fix it!"
     when: item not in ansible_env
     with_items:
       - "PARENT_COMPARTMENT_OCID"
    
   - name: Getting Group ID
     oci_identity_group_facts:
       name: "{{ group_name }}"
       compartment_id: "{{ parent_compartment_ocid }}"
     register: result 
   - set_fact: 
       group_ocid: "{{ result.groups[0].id }}"
  
   - name: Creating users, adding to a group and defining the password
     include_tasks: "tcb-bmc-iam-creating-users.yaml"
     loop: "{{ users }}"

   - name: Send an email to a single recipient that the deployment was successful
   - sendgrid:
      community.general.sendgrid:
      username: 'praful1611@outlook.com'
      password: 'Canada@devops2018'
      from_address: "aystester1@gmail.com"
      to_addresses:
          - "praful9080@gmail.com"
      subject: "Deployment success."
      body: "The most recent Ansible deployment was successful."
    delegate_to: localhost
